ALTER TABLE [dbo].[GiftPurchase]
    ADD CONSTRAINT [PK_GiftPurchase] PRIMARY KEY CLUSTERED ([GiftPurchaseId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

