/*ALTER TABLE [dbo].[GuestPurchase]
    ADD CONSTRAINT [PK_GuestPurchase] PRIMARY KEY CLUSTERED ([GuestPurchaseId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

