ALTER TABLE [dbo].[Guest]
    ADD CONSTRAINT [PK_Guest] PRIMARY KEY CLUSTERED ([GuestId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

